# Generated by Django 4.0.3 on 2022-04-26 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_rename_name_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='LevelPlayedScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField()),
                ('level', models.IntegerField()),
                ('score', models.IntegerField()),
                ('lives', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=500),
        ),
    ]
