# Generated by Django 4.0.3 on 2022-04-26 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_alter_user_password'),
        ('login', '0005_levelplayedscore_alter_user_password'),
    ]

    operations = [
    ]
