# Generated by Django 4.0.3 on 2022-04-27 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_merge_20220426_1219'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopUserScores',
            fields=[
                ('userId', models.IntegerField(primary_key=True, serialize=False)),
                ('scoreLevel1', models.IntegerField()),
                ('scoreLevel2', models.IntegerField()),
                ('scoreLevel3', models.IntegerField()),
                ('scoreLevel4', models.IntegerField()),
            ],
        ),
    ]
