# Generated by Django 4.0.3 on 2022-04-29 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_topuserscores'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryScores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=200)),
                ('score', models.IntegerField()),
            ],
        ),
    ]
