# Generated by Django 4.0.3 on 2022-04-30 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_datagame'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LevelPlayedScore',
        ),
    ]
